# Generated by Django 2.2 on 2023-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='youneed_know',
            new_name='you_need_know',
        ),
        migrations.AddField(
            model_name='course',
            name='is_classics',
            field=models.BooleanField(default=False, verbose_name='Is it classic course'),
        ),
    ]
