# Generated by Django 2.2 on 2023-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20230618_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='Whether advertising space'),
        ),
    ]
