# Generated by Django 2.2 on 2023-06-22 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20230602_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(max_length=200, upload_to='banner/%Y/%m', verbose_name='Rotating Image')),
                ('url', models.URLField(verbose_name='Access Address')),
                ('index', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
